name: catcoder-web
static_sites:
  - name: portfolio
    github:
      branch: main
      deploy_on_push: true
    source_dir: /
    output_dir: dist
    build_command: npm run build
    catchall_document: index.html
    error_document: 404.html
    routes:
      - path: /sw.js
        headers:
          - key: Cache-Control
            value: "max-age=0, no-cache, no-store, must-revalidate"
      - path: /assets
        headers:
          - key: Cache-Control
            value: "public, max-age=31536000, immutable"
      - path: /
        headers:
          - key: Cache-Control
            value: "max-age=0, must-revalidate, public"
